### ISSUE TITLE
(TBD) Deny users from posting if they have more than 5? 10? reports on their account

### ISSUE THREAD

**Issue by JakeSteinebronn** [ucf-tower-app/xplat#195]
Makes sense to me tbh. If you have enough active reports on your account in total, you probably shouldnt be posting

**Comment by Henry-Graves** [comment]
instead of querying Reports and counting the number of reports against a user every time they want to comment/post/edit, maintain a canPost boolean on the User that gets checked/updated on every report (a less frequent event).

- add canPost boolean to User
- add canPost checks/updates to report & absolve functions
- add checkCanPost to EVERY user action that needs it, requires adding a param to all those functions that passes in the current user?

moving this to stretch goals bc I don't want to do all that rn before more important stuff. We'll rely on employees banning people and to-be-banned users not continually spamming bad content. Their OG reported content will get hidden anyway

**Comment by Henry-Graves** [comment]
closing as not planned because it's not explicitly a good addition: people could report bomb a user to unjustly ban them.
For the scope of our app it's fine to let a user keep posting until they hit their media cap or an employee takes their content down. Also the content will be hidden at 5 reports anyway.
