### ISSUE TITLE
modHistoryIQ page docs are arrays of ModActions, rather than individual

### ISSUE THREAD

**Issue by AlexRutledge1** [ucf-tower-app/xplat#241]
In it's current state you cannot call `constructPageData` on a `ModHistory` page because each doc in the page is an array of `ModAction`'s.
Here's a pic of what `queries.ts` tries to parse:

![Image](https://user-images.githubusercontent.com/31017536/221223454-75d4901c-f1e8-4b32-9d8d-bb3b77be2473.png)

**Comment by Henry-Graves** [comment]
Is our intended UI flow the same? I was thinking the modHistoryIQ would get a list of dates action was taken, then you can click into any date and it'll expand to show the list of all modActions taken that day.

For that, I think we need a new IQ over modActions within a day, then call constructPageData on a single modAction. In this case we wouldn't be doing constructPageData on modHistory at all.

Alternatively we can refactor the types so that we can construct a modHistory, no new IQ over modActions, just look at the array on modHistory

**Comment by AlexRutledge1** [comment]
So to be clear, the modHistoryIQ gets a list of dates where a modAction occurred and for each date it has a list of modActions? Just want to make sure I understand as I will create a new class that handles the parsing.

**Comment by Henry-Graves** [comment]
yeah that's all correct, each date is a doc including the array `actions`, where every element is a map with all the relevant info (with consistent fields across all the possible actions)
