### ISSUE TITLE
Post editing

### ISSUE THREAD

**Issue by JakeSteinebronn** [ucf-tower-app/xplat#27]
TSIA

**Comment by TylerMathis** [comment]
Any more info on this? What can a user edit? Can they change the video? Can they move it to a different forum?

**Comment by JakeSteinebronn** [comment]
They can edit text, image, and video content. Not sure why a user would move a post to a different forum, but we won't support that

**Comment by Henry-Graves** [comment]
@JakeSteinebronn @DanielW48 I'd like your thoughts on this, but I'm in favor of not letting users add new images or video content to an existing post. I think it'll be confusing for other users to encounter those edits because a post they interacted with could become about something completeley different. 

Also there's a lot of nuance around someone editing in a controversial image and now everyone who previously liked the image looks like they're supporting that. Instagram handles this by only letting you delete images/videos and showing a new timestamp on any text edits.

If the motive behind post editing is to fix simple mistakes, we could just let the text content be editable (fix typos, etc).

**Comment by DanielW48** [comment]
Agreed, adding media to an existing post sounds no bueno. Deleting could be nice, but it will be a lot of work and it's probably pretty low priority.
